- Assets/PreFabs/EnviromentPieces/Tier.prefab
- Assets/PreFabs/EnviromentPieces/Tier.prefab.meta
- Assets/Scenes/TestingGyms/Tier Gym.unity
- Assets/Scenes/TestingGyms/Tier Gym.unity.meta
- Assets/Scripts/Singleton.cs
- Assets/Scripts/Singleton.cs.meta
- Assets/Scripts/Tier Behaviors.meta
- Assets/Scripts/Tier Behaviors/Tier.cs
- Assets/Scripts/Tier Behaviors/Tier.cs.meta
- Assets/Scripts/Tier Behaviors/TierManager.cs
- Assets/Scripts/Tier Behaviors/TierManager.cs.meta
- Assets/Scripts/Tier Behaviors/Trapdoor.cs
- Assets/Scripts/Tier Behaviors/Trapdoor.cs.meta
in cake tier testing scene, can drag the player through the trapdoors to move between tiers
> Cake tiers

- Assets/PreFabs/EnviromentPieces/Moving Platform.prefab
- Assets/PreFabs/EnviromentPieces/Moving Platform.prefab.meta
- Assets/Scenes/TestingGyms/Moving platforms.unity
- Assets/Scenes/TestingGyms/Moving platforms.unity.meta
- Assets/Scripts/MovingPlatform.cs
- Assets/Scripts/MovingPlatform.cs.meta
test the moving platform in the Moving Platforms Scene. The prefab is in tier one, and you can edit the fields in the inspector to get it to work how you want.
Currently the player is not being moved with the platform. If we want to do that we can change the functinoality later.
> functional moving platform

- Assets/PreFabs/Tiers/Tier 2.prefab
- Assets/Scenes/Layer3GrayBox.unity
- Assets/Scenes/Layer3GrayBox.unity.meta
The orange platforms are where the "slopes" would be, and where the rolling obstacles would spawn.
also idk how to work the trapdoor
> Added Tier3

- Assets/Scenes/Level2Graybox.unity
- Assets/Scenes/Level2Graybox.unity.meta
Found in a scene of the same name. Focuses on moving platforms as requested.
> Layer 2 graybox

- Assets/PreFabs/EnviromentPieces/LaunchPad.prefab
- Assets/PreFabs/EnviromentPieces/LaunchPad.prefab.meta
- Assets/Scenes/TestingGyms/JumpPadTesting.unity
- Assets/Scenes/TestingGyms/JumpPadTesting.unity.meta
- Assets/Scripts/LaunchPad.cs
- Assets/Scripts/LaunchPad.cs.meta
Test in the launch pad testing scene. Worked in the LaunchPad script. There's a variable for how high the player gets launched and a bool that changes how the launch pad works. If true, the player has to land on the pad to be launched. If false, they just have to touch it.
> LaunchPad works and is a prefab

- Assets/PreFabs/Tiers/Strawberry Tier.prefab
- Assets/Scenes/GameScene.unity
Can be Tested in GameScene
Layer adjustments made, everything should be on the right layer now
Softlock with the strawberry tier should now be fixed
> layers unified and minor adjustements throughout to stop soft lock

- Assets/Scenes/TestingGyms/FallinBatterTest.unity
- Assets/Scripts/FallingBatter.cs
- Assets/Scripts/PlayerScripts/PlayerBehaviour.cs
I changed the input to trigger icing falling to E.
> FallingIcing

- Assets/Scenes/GameScene.unity
Can be tested in Game Scene
- Trapdoor functionality should be fixed (Needs further stress testing)
- Timer Updated to reflect 90 second experience
> Trapdoorfix

- Assets/Animations/L5LRollingFruit.anim
- Assets/Animations/L5RRollingFruit.anim
- Assets/Scenes/GameScene.unity
Can be tested in Game Scene
- Updated the Animations of the Rolling Fruits, added spinning anim as well as adjusted the position in tier 5. 
- Fruit still needed in lvl 3, waiting on feedback. 
- Current Times are not the same between the two fruits, might need to bring their frame count in line so they end at the same time.
> rolling fruit animations for level 5 created.

- Assets/PreFabs/EnviromentPieces/L5LRollingFruit.prefab
- Assets/PreFabs/EnviromentPieces/L5RRollingFruit.prefab
- Assets/PreFabs/Player.prefab
- Assets/Scenes/TestingGyms/KnockbackTest.unity
- Assets/Scenes/TestingGyms/KnockbackTest.unity.meta
- Assets/Scripts/FallingBatter.cs
- Assets/Scripts/Platforming types/RollingFruit.cs
- Assets/Scripts/PlayerScripts/PlayerBehaviour.cs
- ProjectSettings/TagManager.asset
Can test changes in KnockbackTest scene
- Added knockback for touching rolling fruits or falling batter
- Invincibility frames, visually indicated by flashing opacity
> Functional knockback and i-frames

- Assets/PreFabs/EnviromentPieces/FallingIcing.prefab
- Assets/PreFabs/EnviromentPieces/SlowField (1).prefab
- Assets/PreFabs/Tiers/Tier 1.prefab
- Assets/PreFabs/Tiers/Tier 2.prefab
- Assets/PreFabs/Tiers/Tier 3.prefab
- Assets/PreFabs/Tiers/Tier 4.prefab
- Assets/PreFabs/Tiers/Tier 5.prefab
- Assets/Scenes/GameScene.unity
I have implemented the falling icing obstacle and rebalanced the fruits in tier 4 as a way to test and see if this is what the team wants going forward
> Falling icing obstacle

- Assets/Scenes/GameScene.unity
Split the middle platform, so players can go back down
> Updated main platform layout

- Assets/PreFabs/EnviromentPieces/CakeFallSquish.playable
- Assets/PreFabs/EnviromentPieces/CakeFallSquish.playable.meta
- Assets/PreFabs/EnviromentPieces/CakeFallingTest.playable
- Assets/PreFabs/EnviromentPieces/CakeFallingTest.playable.meta
- Assets/Scenes/CatMeowTest(SwipeImminent)Timeline.playable
- Assets/Scenes/CatMeowTest(SwipeImminent)Timeline.playable.meta
- Assets/Scenes/GameScene.unity
- Assets/Scenes/TimelineTest.unity
- Assets/Scenes/TimelineTest.unity.meta
- ProjectSettings/TimelineSettings.asset
Can be Tested in GameScene or TimelineTest
- Added a Proof of Concept Intro Cutscene, panning and shirking the camera down until it reaches the player. The door is open to add in floating panels and instructions to teach the player during this.
- Added in cake falling animations, rough idea, to get a sense of feel. Spending most of the animation time on tier 2, and creating placeholder animations for the other tiers to fall. Very much work in progress, meant to be updated later.
Most likely to review tomorrow during class.
> Cake timeline test

- Assets/Scripts/PlayerScripts/PlayerBehaviour.cs
Can be tested in any scene with functional hamster
Changes are explained by pull request title, check code for details
> Jump spam bug fixed

- Assets/PreFabs/EnviromentPieces/FallingIcing.prefab
- Assets/PreFabs/EnviromentPieces/L5LRollingFruit.prefab
- Assets/PreFabs/EnviromentPieces/L5RRollingFruit.prefab
- Assets/PreFabs/Fruits/Blackberry.prefab
- Assets/PreFabs/Fruits/Blueberry.prefab
- Assets/PreFabs/Fruits/Raspberry Variant.prefab
- Assets/PreFabs/Tiers/Tier 1.prefab
- Assets/PreFabs/Tiers/Tier 2.prefab
- Assets/PreFabs/Tiers/Tier 3.prefab
- Assets/PreFabs/Tiers/Tier 4.prefab
- Assets/PreFabs/Tiers/Tier 5.prefab
adjusted the layers of the cake background
> Cake background fix

- Assets/PreFabs/EnviromentPieces/PlatformShadow.prefab
- Assets/PreFabs/EnviromentPieces/PlatformShadow.prefab.meta
- Assets/PreFabs/Tiers/Tier 1.prefab
- Assets/PreFabs/Tiers/Tier 2.prefab
- Assets/PreFabs/Tiers/Tier 3.prefab
- Assets/PreFabs/Tiers/Tier 4.prefab
- Assets/PreFabs/Tiers/Tier 5.prefab
- Assets/Scenes/Layer3GrayBoxRecover.unity
- Assets/Scenes/Level4Graybox.unity
- Assets/Scenes/Level5Graybox.unity
- Assets/Scripts/Platforming types/DisapearingPlatforms.cs
- Added shadows to every platform
- Shadows are prefabs, adjust weight for all shadows at once
- Fixed some platforms that didn't match their collision
> Platform shadows

- Assets/PreFabs/Tiers/Tier 3.prefab
- Assets/PreFabs/Tiers/Tier 4.prefab
- Assets/Scenes/GameScene.unity
- Assets/Scripts/Platforming types/PlayerTransportable.cs
Bugs 9 and 11 in the tracker (fixed their movement of the hamster and a deactivation error)
> Moving platform fixes

- Assets/PreFabs/Player.prefab
- Assets/Scripts/PlayerScripts/PlayerBehaviour.cs
Hamster is dizzy for 1 second (configurable in inspector) after getting hit by something
Hamster turns pink when it is dizzy (waiting for animation)
Hamster is invincible while dizzy, and its I-frame timer properly begins after dizziness ends
> Added dizzy period

- Assets/PreFabs/Tiers/Tier 2.prefab
- Assets/PreFabs/Tiers/Tier 3.prefab
- Assets/PreFabs/Tiers/Tier 4.prefab
reverted moving platforms to the old sprite
> New platform sprites

- Assets/Scripts/Platforming types/MovingPlatform.cs
This was an issue with tiers getting swiped and moving platforms being left behind, it has been fixed
> Moving platforms move with their tiers

- Assets/Assets/Animations/Cutscenes/T2CakeFallTimeline.playable
- Assets/Assets/Animations/Cutscenes/T3CakeFallTimeline.playable
- Assets/Assets/Animations/Cutscenes/T4CakeFallTimeline.playable
- Assets/PreFabs/EnviromentPieces/CakeFallingTest.playable
- Assets/Scenes/GameScene.unity
Can be Tested in GameScene
- Removed the height change that timeline had for each of the tiers.
> No More Movement

- Assets/Animations/L5LRollingFruit.anim
- Assets/Animations/L5RRollingFruit.anim
- Assets/PreFabs/EnviromentPieces/lvl3rollinfruit.anim
Can be tested in GameScene
Adjusted oranges to grow on spawn as well as turn their colliders off at the start and end
> AdjustedOrangeColliders

- Assets/PreFabs/EnviromentPieces/FallingIcing.prefab
- Assets/Scripts/FallingBatter.cs
> AlienBar flashing

- Assets/PreFabs/EnviromentPieces/L3RollingFruit.controller
- Assets/PreFabs/EnviromentPieces/lvl3rollinfruit.anim
Edited animation to switch the direction variable of the level 3 rolling orange at the point that it switches direction
> Fixed level 3 orange direction

- Assets/Assets/Animations/1stStageMultiAnim.anim
- Assets/PreFabs/EnviromentPieces/CakeFallSquish.playable
- Assets/Scenes/GameScene.unity
Can be tested in GameScene
Updated 1stStageMultiAnim animation on Multiplier bar to increase in scale and decrease in scale over the course of .33 seconds as well as added a slight shake back and forth
> Mutiplierbar anims new

- Assets/PreFabs/EnviromentPieces/CakeFallSquish.playable
- Assets/Scenes/GameScene.unity
Can be tested in GameScene
Updated intro cutscene to hold on the strawberry, slowly panning down for 2 seconds before panning to the bottom
Adjusted the timer to match the new time, 8.5 seconds for the intro cutscene
> IntroCutsceneUpdate

- Assets/Scenes/MainMenu.unity
- Assets/Scripts/Leaderboard/DisplayLeaderboard.cs
- Assets/Scripts/Leaderboard/HighestScore.cs
- Assets/Scripts/Leaderboard/HighestScore.cs.meta
Test in the main menu. If there is no leaderboard score, it will say "No High Score Yet!!". If there is a score, it will show that instead.
> Main menu shows the highest leaderboard score

- Assets/Assets/Animations/TimerIntroAnim.anim
- Assets/PreFabs/EnviromentPieces/CakeFallSquish.playable
- Assets/Scenes/GameScene.unity
- Assets/Scripts/Tier Behaviors/TimerSystem.cs
- Assets/Scripts/UIBehaviors/TimerUIAnimEvents.cs
Can be Tested in Game Scene
Updated TimerIntro anim to shake before going up
Added point values to all trapdoors
> timer into updated to shake, Added point values to all trapdoors

- Assets/Assets/Animations/Cutscenes/T4CakeFallTimeline.playable
Can be tested in gamescene
Updated the cake swipe to properly hold the position of Tier4 during swipe
> fixed cake swipe

- Assets/Scripts/Audio/SfxManager.cs
- Assets/Scripts/FruitScripts/ScoreManager.cs
- Assets/Scripts/Tier Behaviors/TierManager.cs
* Fixed final tier index out of bound exception by hardcoding gametier limit to 5
* Removed Debug.Log and Debug messages I have been using
* Adjusted the Star Mode Timing (needs review)
> Fixed Error on 5th tier + visual changes

- Assets/Assets/SpriteSheets/Cat/CatReact_Color1.png.meta
- Assets/Assets/SpriteSheets/Cat/CatReact_Color2.png.meta
- Assets/Assets/SpriteSheets/Cat/CatSwat_0.png.meta
- Assets/Assets/SpriteSheets/Cat/CatSwat_1.png.meta
- Assets/Assets/SpriteSheets/Cat/CatSwat_2.png.meta
- Assets/Assets/SpriteSheets/Cat/CatSwat_3.png.meta
- Assets/Assets/SpriteSheets/Cat/FinalCatSprites/CatReact_Final0.png.meta
- Assets/Assets/SpriteSheets/Cat/FinalCatSprites/CatReact_Final1.png.meta
- Assets/Assets/SpriteSheets/Cat/FinalCatSprites/CatSwat_Final0.png.meta
- Assets/Assets/SpriteSheets/Cat/FinalCatSprites/CatSwat_Final1.png.meta
- Assets/Assets/SpriteSheets/Cat/FinalCatSprites/CatSwat_Final2.png.meta
- Assets/Assets/SpriteSheets/Cat/FinalCatSprites/CatSwat_Final3.png.meta
- Assets/Assets/SpriteSheets/Whiteboards/TutorialBoards_Ver2Sheet1.png.meta
- Assets/Assets/SpriteSheets/Whiteboards/TutorialBoards_Ver2Sheet2.png.meta
- Assets/Assets/SpriteSheets/Whiteboards/TutorialBoards_Ver2Sheet3.png.meta
- Assets/Assets/SpriteSheets/Whiteboards/TutorialBoards_Ver2Sheet4.png.meta
- Assets/Assets/SpriteSheets/Whiteboards/TutorialBoards_Ver2Sheet5.png.meta
- Assets/Assets/SpriteSheets/Whiteboards/TutorialBoards_Ver2Sheet6.png.meta
- Assets/Assets/SpriteSheets/Whiteboards/tutorial.png.meta
- Assets/Assets/SpriteSheets/Whiteboards/whiteboardbyitself.png.meta
Can be tested in HowToPlay Scene
Updated the max resolution of all of the tutorial animations to 8192 (Could go higher if there is still pixelation)
Changed compression to none
Changed filtering more to trilinear
> No longer blurry
